version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Geolocation: The Geolocation microservice
  ###################################
  geolocation:
    build:
      context: ./
      dockerfile: geolocation.Dockerfile
    image: 02031998/gelocation:g9th
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
        - "5001:5001"
 
  #######################################################
  # Ingame_Shop: The Ingame_Shop microservice
  #######################################################
  ingame_shop:
    build:
      context: ./
      dockerfile: ingame_shop.Dockerfile
    image: 02031998/ingame_shop:g9th
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/ingame_shop
      PYTHONUNBUFFERED: 1
    ports:
        - "5005:5005"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # Activity Log: The Activity Log microservice
  #################################################
  activity:
    build:
      context: ./
      dockerfile: activity.Dockerfile
    image: 02031998/activity:g9th
    restart: always
    depends_on:
      - rabbitmq
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/activitylog
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: 02031998/error:g9th
    restart: always
    depends_on:
      - rabbitmq
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/errorlog
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # Box: The Box microservice
  ###############################################
  box:
    build:
      context: ./
      dockerfile: box.Dockerfile
    image: 02031998/box:g9th
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/box
      PYTHONUNBUFFERED: 1
    ports:
        - "5002:5002"


  ##################################
  # User: The User microservice
  ##################################
  user:
    build:
      context: ./
      dockerfile: user.Dockerfile
    image: 02031998/user:g9th
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user
      PYTHONUNBUFFERED: 1
    ports:
        - "5004:5004"

  ###############################################
  # Order: The Order microservice
  ###############################################
  order:
    build:
      context: ./
      dockerfile: order.Dockerfile
    image: 02031998/order:g9th
    restart: always
    depends_on:
      - ingame_shop
      - user
      - activity
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      ingame_shop_URL: http://ingame_shop:5005/order
      user_URL: http://user:5004/user/purchase/
      PYTHONUNBUFFERED: 1
    ports:
        - "5007:5007"
  
  ###############################################
  # Subscription: The Subscription microservice
  ###############################################
  subscription:
    build:
      context: ./
      dockerfile: subscription.Dockerfile
    image: 02031998/subscription:g9th
    restart: always
    depends_on:
      - user
      - activity
      - error
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_URL: http://user:5004/user/membership/
      PYTHONUNBUFFERED: 1
    ports:
        - "5006:5006"

  ###############################################
  # Box_Opening: The Box_Opening microservice
  ###############################################
  box_opening:
    build:
      context: ./
      dockerfile: box_opening.Dockerfile
    image: 02031998/box_opening:g9th
    restart: always
    depends_on:
      - geolocation
      - box
      - user
      - activity
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      geolocation_URL: http://geolocation:5001/
      box_nearest_URL: http://box:5002/search?latitude=
      box_update_URL: http://box:5002/open
      user_URL: http://user:5004/user/openbox/
      PYTHONUNBUFFERED: 1
    ports:
        - "5003:5003"

  ###############################################
  # Create_Box: The Create_Box microservice
  ###############################################
  create_box:
    build:
      context: ./
      dockerfile: create_box.Dockerfile
    image: 02031998/create_box:g9th
    restart: always
    depends_on:
      - geolocation
      - box
      - activity
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      geolocation_URL: http://geolocation:5001/
      box_create_URL: http://box:5002/
      PYTHONUNBUFFERED: 1
    ports:
        - "5008:5008"